/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { ChannelWhereUniqueInput } from "../../channel/base/ChannelWhereUniqueInput";
import { EnumVideoPrivacyStatus } from "./EnumVideoPrivacyStatus";
import { EnumVideoTags } from "./EnumVideoTags";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class VideoUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ChannelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ChannelWhereUniqueInput)
  @IsOptional()
  @Field(() => ChannelWhereUniqueInput, {
    nullable: true,
  })
  channel?: ChannelWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumVideoPrivacyStatus,
  })
  @IsEnum(EnumVideoPrivacyStatus)
  @IsOptional()
  @Field(() => EnumVideoPrivacyStatus, {
    nullable: true,
  })
  privacyStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumVideoTags,
    isArray: true,
  })
  @IsEnum(EnumVideoTags, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumVideoTags], {
    nullable: true,
  })
  tags?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  videoFile?: InputJsonValue;
}

export { VideoUpdateInput as VideoUpdateInput };
